"""Shared environment gates and bounded execution defaults for load workflows."""

MUTATION_FLAG = "PM8_ALLOW_MUTATIONS"
EXTENDED_FLAG = "PM8_ALLOW_EXTENDED_TESTS"
STEP_LOAD_FLAG = "PM9_ALLOW_CAPACITY_TESTS"
DEFAULT_SHUTDOWN_GRACE_SECONDS = 2.0
DEFAULT_TELEMETRY_INTERVAL_SECONDS = 1.0
DEFAULT_MONITOR_INTERVAL_SECONDS = 0.25
MAX_IN_FLIGHT_MULTIPLIER = 2
MIN_REQUEST_TIMEOUT_SECONDS = 0.05
