"""Compatibility facade for the split maintenance API contracts.

Contract definitions live beside their route family. Existing imports from
``src.maintenance_management.schemas`` remain supported for callers, tests,
and generated integrations.
"""

from src.maintenance_management.attachment_schemas import WorkOrderAttachmentResponse
from src.maintenance_management.checklist_schemas import (
    ChecklistTemplateCreateRequest,
    ChecklistTemplateItemRequest,
    ChecklistTemplateItemResponse,
    ChecklistTemplatePage,
    ChecklistTemplateResponse,
    ChecklistTemplateVersionRequest,
)
from src.maintenance_management.plan_schemas import (
    GenerationPlanReport,
    GenerationRequest,
    GenerationResponse,
    MaintenancePlanArchiveRequest,
    MaintenancePlanCreateRequest,
    MaintenancePlanFields,
    MaintenancePlanPage,
    MaintenancePlanResponse,
    MaintenancePlanResumeRequest,
    MaintenancePlanUpdateRequest,
    OccurrenceItem,
    OccurrencePreviewResponse,
)
from src.maintenance_management.schema_types import (
    ChecklistResponseTypeCode,
    ChecklistResultCode,
    IntervalUnitCode,
    MaintenanceResultCode,
    MaintenanceOptionsResponse,
    OptionRecord,
    PlanStatusCode,
    PriorityCode,
    TechnicianOption,
    VersionRequest,
    WorkOrderStatusCode,
    WorkOrderTypeCode,
)
from src.maintenance_management.work_order_schemas import (
    CalendarOccurrence,
    CorrectiveWorkOrderCreateRequest,
    ScheduleViewResponse,
    WorkOrderAssignRequest,
    WorkOrderCancelRequest,
    WorkOrderChecklistItemResponse,
    WorkOrderChecklistResponseRequest,
    WorkOrderChecklistUpdateRequest,
    WorkOrderCompleteRequest,
    WorkOrderCreateRequest,
    WorkOrderHistoryItem,
    WorkOrderMetricsResponse,
    WorkOrderPage,
    WorkOrderReopenRequest,
    WorkOrderResponse,
    WorkOrderTransitionRequest,
    WorkOrderUpdateRequest,
)

__all__ = [
    "CalendarOccurrence",
    "ChecklistResponseTypeCode",
    "ChecklistResultCode",
    "ChecklistTemplateCreateRequest",
    "ChecklistTemplateItemRequest",
    "ChecklistTemplateItemResponse",
    "ChecklistTemplatePage",
    "ChecklistTemplateResponse",
    "ChecklistTemplateVersionRequest",
    "CorrectiveWorkOrderCreateRequest",
    "GenerationPlanReport",
    "GenerationRequest",
    "GenerationResponse",
    "IntervalUnitCode",
    "MaintenanceOptionsResponse",
    "MaintenancePlanArchiveRequest",
    "MaintenancePlanCreateRequest",
    "MaintenancePlanFields",
    "MaintenancePlanPage",
    "MaintenancePlanResponse",
    "MaintenancePlanResumeRequest",
    "MaintenancePlanUpdateRequest",
    "MaintenanceResultCode",
    "OccurrenceItem",
    "OccurrencePreviewResponse",
    "OptionRecord",
    "PlanStatusCode",
    "PriorityCode",
    "ScheduleViewResponse",
    "TechnicianOption",
    "VersionRequest",
    "WorkOrderAssignRequest",
    "WorkOrderCancelRequest",
    "WorkOrderChecklistItemResponse",
    "WorkOrderChecklistResponseRequest",
    "WorkOrderChecklistUpdateRequest",
    "WorkOrderCompleteRequest",
    "WorkOrderCreateRequest",
    "WorkOrderAttachmentResponse",
    "WorkOrderHistoryItem",
    "WorkOrderMetricsResponse",
    "WorkOrderPage",
    "WorkOrderReopenRequest",
    "WorkOrderResponse",
    "WorkOrderStatusCode",
    "WorkOrderTransitionRequest",
    "WorkOrderTypeCode",
    "WorkOrderUpdateRequest",
]
