import type {
  AssetDetailsResponse,
  AssetOverviewRecord,
  AssetProfile,
  MaintenanceLogRecord,
  PreventiveRecord,
  RecurringIssueRecord,
  RiskRecord,
  TicketRecord,
} from "@/lib/api/schemas";

export const healthFixture = {
  status: "ok",
  raw_data_available: true,
  analytics_available: true,
};

export const summaryFixture = {
  total_assets: 2,
  total_records: 240,
  high_risk_count: 1,
  urgent_risk_count: 0,
  anomaly_count: 1,
  latest_date: "2026-04-30",
  average_risk_score: 42.5,
};

export const kpiFixture = {
  as_of_date: "2026-04-30",
  total_tickets: 2,
  open_tickets: 1,
  resolved_tickets: 1,
  ticket_resolution_rate_percent: 50,
  average_resolution_time_hours: 24,
  median_resolution_time_hours: 24,
  overdue_asset_count: 1,
  due_soon_asset_count: 0,
  recurring_issue_count: 1,
  follow_up_required_maintenance_count: 1,
  high_critical_risk_asset_count: 1,
};

export const assetsFixture: AssetOverviewRecord[] = [
  {
    asset_id: "GENERATOR_002",
    asset_name: "Máy phát điện dự phòng 002",
    asset_type: "Máy phát điện dự phòng",
    location: "Sân thượng phía Đông",
    criticality: "Rất quan trọng",
    status: "Cảnh báo",
    installation_date: "2018-08-26",
    last_maintenance_date: "2025-07-25",
    maintenance_interval_days: 120,
    next_maintenance_date: "2025-11-22",
    risk_score: 63.89,
    risk_level_code: "high",
    risk_level: "Cao",
    contributing_factors: "Thiết bị đã quá hạn bảo trì 159 ngày.",
    recommended_action: "Kiểm tra ắc quy và chạy thử tải.",
    maintenance_status: "overdue",
    maintenance_status_display: "Quá hạn",
    days_until_due: 0,
    days_overdue: 159,
    unresolved_ticket_count: 1,
  },
  {
    asset_id: "HVAC_001",
    asset_name: "Máy lạnh 001",
    asset_type: "Máy lạnh",
    location: "Sân thượng phía Tây",
    criticality: "Cao",
    status: "Bình thường",
    installation_date: "2023-04-17",
    last_maintenance_date: "2026-04-03",
    maintenance_interval_days: 90,
    next_maintenance_date: "2026-07-02",
    risk_score: 21.5,
    risk_level_code: "low",
    risk_level: "Thấp",
    contributing_factors: "Không có tín hiệu ưu tiên cao.",
    recommended_action: "Tiếp tục theo dõi.",
    maintenance_status: "not_due",
    maintenance_status_display: "Chưa đến hạn",
    days_until_due: 63,
    days_overdue: 0,
    unresolved_ticket_count: 0,
  },
];

export const locationFixture = {
  id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
  code: "ROOFTOP-EAST",
  name: "Sân thượng phía Đông",
  location_type: "area",
  location_type_display: "Khu vực",
  parent_id: null,
  breadcrumb: "Cơ sở chính / Sân thượng phía Đông",
  description: null,
  is_active: true,
  asset_count: 1,
  created_at: "2026-07-18T00:00:00Z",
  updated_at: "2026-07-18T00:00:00Z",
  version: 1,
};

export const assetProfileFixture: AssetProfile = {
  ...assetsFixture[0],
  asset_type_code: "generator",
  asset_category: "power_system",
  asset_category_display: "Hệ thống điện",
  manufacturer: "Cummins",
  model: "C150D5",
  serial_number: "GEN-002-2018",
  production_year: 2018,
  location_id: locationFixture.id,
  location_breadcrumb: locationFixture.breadcrumb,
  criticality_code: "critical",
  lifecycle_status: "active",
  lifecycle_status_display: "Đang hoạt động",
  lifecycle_status_before_archive: null,
  operational_status: "warning",
  operational_status_display: "Cảnh báo",
  operational_status_before_archive: null,
  installed_at: "2018-08-26T00:00:00Z",
  commissioned_at: "2018-08-30T00:00:00Z",
  retired_at: null,
  archived_at: null,
  archive_reason: null,
  ownership_type: "owned",
  ownership_type_display: "Sở hữu",
  description: "Máy phát điện dự phòng cho tải thiết yếu.",
  warranty_start_date: "2018-08-30",
  warranty_end_date: "2023-08-30",
  warranty_provider: "Nhà cung cấp mẫu",
  warranty_reference: "WR-GEN-002",
  created_at: "2026-07-18T00:00:00Z",
  updated_at: "2026-07-18T00:00:00Z",
  created_by_user_id: null,
  updated_by_user_id: null,
  version: 1,
  qr_lookup_token: "22222222-2222-4222-8222-222222222222",
};

export const hvacProfileFixture: AssetProfile = {
  ...assetProfileFixture,
  ...assetsFixture[1],
  asset_type_code: "hvac",
  asset_category: "climate_control",
  asset_category_display: "Điều hòa không khí",
  manufacturer: "Daikin",
  model: "VRV-IV",
  serial_number: "HVAC-001-2023",
  production_year: 2023,
  location_id: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
  location_breadcrumb: "Cơ sở chính / Sân thượng phía Tây",
  criticality_code: "high",
  operational_status: "running",
  operational_status_display: "Đang vận hành",
  installed_at: "2023-04-17T00:00:00Z",
  commissioned_at: "2023-04-20T00:00:00Z",
  warranty_start_date: "2023-04-20",
  warranty_end_date: "2028-04-20",
  warranty_reference: "WR-HVAC-001",
  version: 2,
  qr_lookup_token: "33333333-3333-4333-8333-333333333333",
};

export const assetCatalogFixture = {
  items: [assetProfileFixture, hvacProfileFixture],
  page: 1,
  page_size: 10,
  total: 2,
  total_pages: 1,
};

export const assetOptionsFixture = {
  asset_types: [
    { code: "hvac", display_name: "Máy lạnh" },
    { code: "pump", display_name: "Máy bơm" },
    { code: "generator", display_name: "Máy phát điện dự phòng" },
  ],
  asset_categories: [
    { code: "climate_control", display_name: "Điều hòa không khí" },
    { code: "water_system", display_name: "Hệ thống nước" },
    { code: "power_system", display_name: "Hệ thống điện" },
    { code: "other", display_name: "Khác" },
  ],
  criticalities: [
    { code: "low", display_name: "Thấp" },
    { code: "medium", display_name: "Trung bình" },
    { code: "high", display_name: "Cao" },
    { code: "critical", display_name: "Rất quan trọng" },
  ],
  lifecycle_statuses: [
    { code: "planned", display_name: "Đang lập kế hoạch" },
    { code: "active", display_name: "Đang hoạt động" },
    { code: "inactive", display_name: "Tạm ngừng" },
    { code: "retired", display_name: "Đã ngừng sử dụng" },
    { code: "archived", display_name: "Đã lưu trữ" },
  ],
  operational_statuses: [
    { code: "running", display_name: "Đang vận hành" },
    { code: "warning", display_name: "Cảnh báo" },
    { code: "fault", display_name: "Có lỗi" },
    { code: "under_maintenance", display_name: "Đang bảo trì" },
    { code: "out_of_service", display_name: "Ngừng phục vụ" },
  ],
  ownership_types: [
    { code: "owned", display_name: "Sở hữu" },
    { code: "leased", display_name: "Thuê" },
    { code: "managed", display_name: "Quản lý hộ" },
  ],
  location_types: [{ code: "area", display_name: "Khu vực" }],
  attachment_categories: [
    { code: "asset_photo", display_name: "Ảnh thiết bị" },
    { code: "technical_manual", display_name: "Tài liệu kỹ thuật" },
    { code: "warranty_document", display_name: "Tài liệu bảo hành" },
    { code: "commissioning_record", display_name: "Biên bản nghiệm thu" },
    { code: "inspection_document", display_name: "Biên bản kiểm tra" },
    { code: "other", display_name: "Khác" },
  ],
};

export const assetQrFixture = {
  asset_id: "GENERATOR_002",
  lookup_token: assetProfileFixture.qr_lookup_token,
  lookup_url: `http://localhost:3000/scan/assets/${assetProfileFixture.qr_lookup_token}`,
  svg_base64: "PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjwvc3ZnPg==",
  label_text: "GENERATOR_002 · Máy phát điện dự phòng 002",
};

export const assetHistoryFixture = {
  items: [
    {
      id: "audit-asset-created",
      occurred_at: "2026-07-18T00:00:00Z",
      action: "asset.created",
      event_type: "asset",
      summary: "Đã đăng ký asset GENERATOR_002.",
      actor_user_id: null,
      actor_display_name: null,
      resource_type: "asset",
      resource_id: "GENERATOR_002",
      changed_fields: ["asset_name", "location_id"],
    },
  ],
  page: 1,
  page_size: 15,
  total: 1,
  total_pages: 1,
};

export const ticketsFixture: TicketRecord[] = [
  {
    ticket_id: "TCK-000041",
    asset_id: "GENERATOR_002",
    issue_description: "Máy phát ghi nhận cảnh báo điện trong lần kiểm tra gần nhất.",
    priority: "Khẩn cấp",
    status: "Mới tạo",
    failure_category: "Lỗi điện",
    created_at: "2026-04-26T13:35:00+00:00",
    resolved_at: null,
    technician_id: "TECH_003",
    manager_note: null,
    note: null,
  },
  {
    ticket_id: "TCK-000010",
    asset_id: "HVAC_001",
    issue_description: "Đã vệ sinh lưới lọc.",
    priority: "Thấp",
    status: "Đã xử lý",
    failure_category: "Lỗi làm lạnh",
    created_at: "2026-03-01T08:00:00+00:00",
    resolved_at: "2026-03-02T08:00:00+00:00",
    technician_id: "TECH_001",
    manager_note: null,
    note: null,
  },
];

export const riskFixture: RiskRecord = {
  asset_id: "GENERATOR_002",
  date: "2026-04-30",
  asset_name: "Máy phát điện dự phòng 002",
  asset_type: "Máy phát điện dự phòng",
  location: "Sân thượng phía Đông",
  anomaly_score: 29.47,
  maintenance_overdue_score: 100,
  recent_ticket_score: 80,
  criticality_score: 100,
  runtime_score: 0,
  final_risk_score: 63.89,
  risk_level: "Cao",
  main_reasons: "Thiết bị đã quá hạn bảo trì 159 ngày.",
  recommended_action: "Kiểm tra ắc quy và chạy thử tải.",
  unresolved_ticket_score: 75,
  recurring_issue_score: 0,
  follow_up_score: 0,
  risk_score: 63.89,
  risk_level_code: "high",
  contributing_factors: "Thiết bị đã quá hạn bảo trì 159 ngày.",
};

export const anomalyFixture = {
  asset_id: "GENERATOR_002",
  date: "2026-04-21",
  asset_type: "Máy phát điện dự phòng",
  location: "Sân thượng phía Đông",
  energy_kwh: 111.159,
  temperature: 32.3,
  vibration: 0.2,
  runtime_hours: 7.681,
  pressure: 0,
  energy_delta_percent: 54.7,
  vibration_delta: 0.04,
  runtime_delta_percent: 57.8,
  rule_based_score: 94.4,
  isolation_forest_score: 98.3,
  anomaly_score: 95.62,
  is_anomaly: true,
  anomaly_type: "Thời gian vận hành bất thường",
  anomaly_reasons: "Điện năng và thời gian vận hành tăng so với mức nền.",
  anomalous_metrics: "energy_kwh, runtime_hours",
};

export const preventiveFixture: PreventiveRecord[] = [
  {
    asset_id: "GENERATOR_002",
    as_of_date: "2026-04-30",
    last_maintenance_date: "2025-07-25",
    next_maintenance_date: "2025-11-22",
    days_until_due: 0,
    days_overdue: 159,
    maintenance_status: "overdue",
    maintenance_status_display: "Quá hạn",
  },
  {
    asset_id: "HVAC_001",
    as_of_date: "2026-04-30",
    last_maintenance_date: "2026-04-03",
    next_maintenance_date: "2026-07-02",
    days_until_due: 63,
    days_overdue: 0,
    maintenance_status: "not_due",
    maintenance_status_display: "Chưa đến hạn",
  },
];

export const recurringFixture: RecurringIssueRecord = {
  asset_id: "HVAC_001",
  failure_category: "Lỗi làm lạnh",
  occurrence_count: 4,
  first_occurrence: "2026-03-17T07:05:00+00:00",
  last_occurrence: "2026-04-16T11:18:00+00:00",
  resolved_count: 3,
  unresolved_count: 1,
  recurrence_flag: true,
  recurrence_threshold: 3,
};

export const logFixture: MaintenanceLogRecord = {
  log_id: "LOG-000001",
  ticket_id: null,
  asset_id: "GENERATOR_002",
  maintenance_date: "2025-07-25",
  maintenance_type: "Bảo trì định kỳ",
  technician_id: "TECH_005",
  inspection_result: "Thiết bị đạt yêu cầu kiểm tra.",
  actions_taken: "Kiểm tra ắc quy, dầu nhớt và chạy thử máy phát.",
  parts_replaced: null,
  technician_note: "Đã hoàn tất kiểm tra.",
  maintenance_result: "Đã xử lý",
  follow_up_required: false,
  next_maintenance_date: "2025-11-22",
};

export const assetDetailsFixture: AssetDetailsResponse = {
  asset_profile: {
    asset_id: assetsFixture[0].asset_id,
    asset_name: assetsFixture[0].asset_name,
    asset_type: assetsFixture[0].asset_type,
    location: assetsFixture[0].location,
    criticality: assetsFixture[0].criticality,
    status: assetsFixture[0].status,
    installation_date: assetsFixture[0].installation_date,
    last_maintenance_date: assetsFixture[0].last_maintenance_date,
    maintenance_interval_days: assetsFixture[0].maintenance_interval_days,
    next_maintenance_date: assetsFixture[0].next_maintenance_date,
  },
  latest_risk: riskFixture,
  risk_contributing_factors: riskFixture.contributing_factors ?? null,
  recommended_action: riskFixture.recommended_action,
  preventive_maintenance: preventiveFixture[0],
  risk_history: [riskFixture],
  recent_anomalies: [anomalyFixture],
  recent_tickets: [ticketsFixture[0]],
  recent_maintenance_logs: [logFixture],
  recurring_issues: [recurringFixture],
};

export const copilotResponseFixture = {
  answer: [
    "### Tóm tắt tình trạng thiết bị",
    "GENERATOR_002 cần được kiểm tra theo risk context hiện tại.",
    "### Checklist hoặc bước kiểm tra được tìm thấy",
    "- Cô lập thiết bị và xác nhận điều kiện an toàn.",
    "- Đo điện áp ắc quy theo SOP.",
    "### Nguồn tài liệu",
    "Xem danh sách nguồn.",
    "### Lưu ý an toàn",
    "Tuân thủ quy trình an toàn.",
    "### Giới hạn của khuyến nghị",
    "Kỹ thuật viên phải xác minh tại hiện trường.",
  ].join("\n"),
  asset_context: { asset_id: "GENERATOR_002", asset_type: "Máy phát điện dự phòng" },
  sources: [
    {
      doc_id: "SOP-GEN-001",
      document_id: "SOP-GEN-001",
      title: "SOP kiểm tra máy phát điện dự phòng",
      doc_type: "SOP",
      document_type: "SOP",
      asset_type: "Máy phát điện dự phòng",
      failure_category: "Lỗi điện",
      version: "1.0",
      effective_date: "2026-01-15",
      source: "data/documents/sop_generator.md",
      score: 0.91,
      citation_ids: ["S1"],
    },
  ],
  retrieved_chunks: [
    {
      doc_id: "SOP-GEN-001",
      document_id: "SOP-GEN-001",
      chunk_id: "SOP-GEN-001-0",
      title: "SOP kiểm tra máy phát điện dự phòng",
      doc_type: "SOP",
      document_type: "SOP",
      asset_type: "Máy phát điện dự phòng",
      failure_category: "Lỗi điện",
      version: "1.0",
      effective_date: "2026-01-15",
      source: "data/documents/sop_generator.md",
      score: 0.91,
      text: "Đo điện áp ắc quy.",
      content: "Đo điện áp ắc quy.",
      chunk_index: 0,
      citation_id: "S1",
    },
  ],
  retrieval_status: "success" as const,
  relevance_status: "relevant" as const,
  safety_notice: "Ngắt nguồn và tuân thủ lockout/tagout trước khi kiểm tra.",
  filters_applied: { asset_type: "Máy phát điện dự phòng", failure_category: "Lỗi điện" },
  response_mode: "llm_grounded" as const,
  fallback_reason: null,
  structured_answer: {
    summary: "GENERATOR_002 cần được kiểm tra theo SOP đã truy xuất.",
    summary_source_ids: ["S1"],
    possible_causes: [],
    recommended_checks: [
      { text: "Đo điện áp ắc quy theo SOP.", source_ids: ["S1"] },
    ],
    safety_warnings: [
      { text: "Cô lập thiết bị trước khi kiểm tra.", source_ids: ["S1"] },
    ],
    escalation_required: false,
    source_ids: ["S1"],
    confidence: "medium" as const,
    insufficient_evidence: false,
  },
  llm_provider: "ollama",
  llm_model: "demo-model",
  evidence_status: "sufficient" as const,
  citation_validation: {
    valid: true,
    cited_source_ids: ["S1"],
    invalid_source_ids: [],
    coverage_complete: true,
  },
  context_warnings: [],
  conversation_state: {
    recent_intent: "troubleshooting",
    resolved_asset_id: "GENERATOR_002",
    resolved_asset_type: "Máy phát điện dự phòng",
    resolved_failure_category: "Lỗi điện",
    previous_source_ids: ["S1"],
    previous_answer_summary: "Tóm tắt lượt trước do backend xác nhận.",
  },
  diagnostics: {
    request_id: "fixture-request",
    route_status: "supported",
    intent: "troubleshooting",
    filters_present: { asset_type: true, failure_category: true },
    relaxation_steps: [],
    candidate_count: 1,
    relevant_count: 1,
    document_count: 1,
    latency_ms: { routing: 1, retrieval: 2, reranking: 3, generation: 4, total: 10 },
    response_mode: "llm_grounded",
    fallback_reason: null,
    provider: "ollama",
    model: "demo-model",
    citation_status: "valid",
    provider_failure_category: null,
  },
};

export const copilotUnavailableFixture = {
  ...copilotResponseFixture,
  answer: [
    "### Tóm tắt tình trạng thiết bị",
    "Chưa thể truy xuất tài liệu lúc này.",
    "### Giới hạn của khuyến nghị",
    "Không cung cấp hướng dẫn kỹ thuật khi retrieval chưa sẵn sàng.",
  ].join("\n"),
  sources: [],
  retrieved_chunks: [],
  retrieval_status: "unavailable" as const,
  relevance_status: "not_relevant" as const,
  response_mode: "deterministic_fallback" as const,
  fallback_reason: "unavailable",
  structured_answer: null,
  llm_provider: null,
  llm_model: null,
  evidence_status: "insufficient" as const,
  citation_validation: null,
  conversation_state: null,
};
