export const healthFixture = {
  status: "ok",
  raw_data_available: true,
  analytics_available: true,
};

export const summaryFixture = {
  total_assets: 2,
  total_records: 240,
  high_risk_count: 1,
  urgent_risk_count: 0,
  anomaly_count: 1,
  latest_date: "2026-04-30",
  average_risk_score: 42.5,
};

export const kpiFixture = {
  as_of_date: "2026-04-30",
  total_tickets: 2,
  open_tickets: 1,
  resolved_tickets: 1,
  ticket_resolution_rate_percent: 50,
  average_resolution_time_hours: 24,
  median_resolution_time_hours: 24,
  overdue_asset_count: 1,
  due_soon_asset_count: 0,
  recurring_issue_count: 1,
  follow_up_required_maintenance_count: 1,
  high_critical_risk_asset_count: 1,
};

export const assetsFixture = [
  {
    asset_id: "GENERATOR_002",
    asset_name: "Máy phát điện dự phòng 002",
    asset_type: "Máy phát điện dự phòng",
    location: "Sân thượng phía Đông",
    criticality: "Rất quan trọng",
    status: "Cảnh báo",
    installation_date: "2018-08-26",
    last_maintenance_date: "2025-07-25",
    maintenance_interval_days: 120,
    next_maintenance_date: "2025-11-22",
    risk_score: 63.89,
    risk_level_code: "high",
    risk_level: "Cao",
    contributing_factors: "Thiết bị đã quá hạn bảo trì 159 ngày.",
    recommended_action: "Kiểm tra ắc quy và chạy thử tải.",
    maintenance_status: "overdue",
    maintenance_status_display: "Quá hạn",
    days_until_due: 0,
    days_overdue: 159,
    unresolved_ticket_count: 1,
  },
  {
    asset_id: "HVAC_001",
    asset_name: "Máy lạnh 001",
    asset_type: "Máy lạnh",
    location: "Sân thượng phía Tây",
    criticality: "Cao",
    status: "Bình thường",
    installation_date: "2023-04-17",
    last_maintenance_date: "2026-04-03",
    maintenance_interval_days: 90,
    next_maintenance_date: "2026-07-02",
    risk_score: 21.5,
    risk_level_code: "low",
    risk_level: "Thấp",
    contributing_factors: "Không có tín hiệu ưu tiên cao.",
    recommended_action: "Tiếp tục theo dõi.",
    maintenance_status: "not_due",
    maintenance_status_display: "Chưa đến hạn",
    days_until_due: 63,
    days_overdue: 0,
    unresolved_ticket_count: 0,
  },
];

export const ticketsFixture = [
  {
    ticket_id: "TCK-000041",
    asset_id: "GENERATOR_002",
    issue_description: "Máy phát ghi nhận cảnh báo điện trong lần kiểm tra gần nhất.",
    priority: "Khẩn cấp",
    status: "Mới tạo",
    failure_category: "Lỗi điện",
    created_at: "2026-04-26T13:35:00+00:00",
    resolved_at: null,
    technician_id: "TECH_003",
    manager_note: null,
    note: null,
  },
  {
    ticket_id: "TCK-000010",
    asset_id: "HVAC_001",
    issue_description: "Đã vệ sinh lưới lọc.",
    priority: "Thấp",
    status: "Đã xử lý",
    failure_category: "Lỗi làm lạnh",
    created_at: "2026-03-01T08:00:00+00:00",
    resolved_at: "2026-03-02T08:00:00+00:00",
    technician_id: "TECH_001",
    manager_note: null,
    note: null,
  },
];

export const riskFixture = {
  asset_id: "GENERATOR_002",
  date: "2026-04-30",
  asset_name: "Máy phát điện dự phòng 002",
  asset_type: "Máy phát điện dự phòng",
  location: "Sân thượng phía Đông",
  anomaly_score: 29.47,
  maintenance_overdue_score: 100,
  recent_ticket_score: 80,
  criticality_score: 100,
  runtime_score: 0,
  final_risk_score: 63.89,
  risk_level: "Cao",
  main_reasons: "Thiết bị đã quá hạn bảo trì 159 ngày.",
  recommended_action: "Kiểm tra ắc quy và chạy thử tải.",
  unresolved_ticket_score: 75,
  recurring_issue_score: 0,
  follow_up_score: 0,
  risk_score: 63.89,
  risk_level_code: "high",
  contributing_factors: "Thiết bị đã quá hạn bảo trì 159 ngày.",
};

export const anomalyFixture = {
  asset_id: "GENERATOR_002",
  date: "2026-04-21",
  asset_type: "Máy phát điện dự phòng",
  location: "Sân thượng phía Đông",
  energy_kwh: 111.159,
  temperature: 32.3,
  vibration: 0.2,
  runtime_hours: 7.681,
  pressure: 0,
  energy_delta_percent: 54.7,
  vibration_delta: 0.04,
  runtime_delta_percent: 57.8,
  rule_based_score: 94.4,
  isolation_forest_score: 98.3,
  anomaly_score: 95.62,
  is_anomaly: true,
  anomaly_type: "Thời gian vận hành bất thường",
  anomaly_reasons: "Điện năng và thời gian vận hành tăng so với mức nền.",
  anomalous_metrics: "energy_kwh, runtime_hours",
};

export const preventiveFixture = [
  {
    asset_id: "GENERATOR_002",
    as_of_date: "2026-04-30",
    last_maintenance_date: "2025-07-25",
    next_maintenance_date: "2025-11-22",
    days_until_due: 0,
    days_overdue: 159,
    maintenance_status: "overdue",
    maintenance_status_display: "Quá hạn",
  },
  {
    asset_id: "HVAC_001",
    as_of_date: "2026-04-30",
    last_maintenance_date: "2026-04-03",
    next_maintenance_date: "2026-07-02",
    days_until_due: 63,
    days_overdue: 0,
    maintenance_status: "not_due",
    maintenance_status_display: "Chưa đến hạn",
  },
];

export const recurringFixture = {
  asset_id: "HVAC_001",
  failure_category: "Lỗi làm lạnh",
  occurrence_count: 4,
  first_occurrence: "2026-03-17T07:05:00+00:00",
  last_occurrence: "2026-04-16T11:18:00+00:00",
  resolved_count: 3,
  unresolved_count: 1,
  recurrence_flag: true,
  recurrence_threshold: 3,
};

export const logFixture = {
  log_id: "LOG-000001",
  ticket_id: null,
  asset_id: "GENERATOR_002",
  maintenance_date: "2025-07-25",
  maintenance_type: "Bảo trì định kỳ",
  technician_id: "TECH_005",
  inspection_result: "Thiết bị đạt yêu cầu kiểm tra.",
  actions_taken: "Kiểm tra ắc quy, dầu nhớt và chạy thử máy phát.",
  parts_replaced: null,
  technician_note: "Đã hoàn tất kiểm tra.",
  maintenance_result: "Đã xử lý",
  follow_up_required: false,
  next_maintenance_date: "2025-11-22",
};

export const assetDetailsFixture = {
  asset_profile: {
    asset_id: assetsFixture[0].asset_id,
    asset_name: assetsFixture[0].asset_name,
    asset_type: assetsFixture[0].asset_type,
    location: assetsFixture[0].location,
    criticality: assetsFixture[0].criticality,
    status: assetsFixture[0].status,
    installation_date: assetsFixture[0].installation_date,
    last_maintenance_date: assetsFixture[0].last_maintenance_date,
    maintenance_interval_days: assetsFixture[0].maintenance_interval_days,
    next_maintenance_date: assetsFixture[0].next_maintenance_date,
  },
  latest_risk: riskFixture,
  risk_contributing_factors: riskFixture.contributing_factors,
  recommended_action: riskFixture.recommended_action,
  preventive_maintenance: preventiveFixture[0],
  risk_history: [riskFixture],
  recent_anomalies: [anomalyFixture],
  recent_tickets: [ticketsFixture[0]],
  recent_maintenance_logs: [logFixture],
  recurring_issues: [recurringFixture],
};
