export const inventoryIds = {
  category: "10000000-0000-4000-8000-000000000001",
  unit: "10000000-0000-4000-8000-000000000002",
  part: "10000000-0000-4000-8000-000000000003",
  location: "10000000-0000-4000-8000-000000000004",
  destination: "10000000-0000-4000-8000-000000000005",
  position: "10000000-0000-4000-8000-000000000006",
  movement: "10000000-0000-4000-8000-000000000007",
  workOrder: "10000000-0000-4000-8000-000000000008",
  requirement: "10000000-0000-4000-8000-000000000009",
  reservation: "10000000-0000-4000-8000-00000000000a",
  reservationEvent: "10000000-0000-4000-8000-00000000000b",
  issue: "10000000-0000-4000-8000-00000000000c",
  consumption: "10000000-0000-4000-8000-00000000000d",
  return: "10000000-0000-4000-8000-00000000000e",
  user: "10000000-0000-4000-8000-00000000000f",
};

export const stockLocationFixture = {
  id: inventoryIds.location,
  code: "KHO-KT",
  name: "Kho kỹ thuật",
  location_type: "engineering_store",
  location_type_display: "Kho kỹ thuật",
  description: "Kho dùng cho bảo trì.",
  lifecycle_status: "active",
  lifecycle_status_display: "Đang hoạt động",
  archived_at: null,
  archive_reason: null,
  version: 1,
  created_at: "2026-07-23T00:00:00Z",
  updated_at: "2026-07-23T00:00:00Z",
} as const;

export const partFixture = {
  id: inventoryIds.part,
  part_number: "GEN-FILTER-001",
  name_vi: "Lọc dầu máy phát",
  name_en: "Generator oil filter",
  category_id: inventoryIds.category,
  category_code: "FILTER",
  category_name_vi: "Bộ lọc",
  unit_of_measure_id: inventoryIds.unit,
  unit_code: "EA",
  unit_name_vi: "Cái",
  unit_symbol: "cái",
  quantity_precision: 0,
  manufacturer_reference: "REF-001",
  compatible_asset_types: ["generator"],
  lifecycle_status: "active",
  lifecycle_status_display: "Đang hoạt động",
  minimum_stock: 2,
  reorder_point: 4,
  maximum_stock: 12,
  unit_cost: 250000,
  currency_code: "VND",
  total_on_hand_quantity: 3,
  total_reserved_quantity: 1,
  total_available_quantity: 2,
  stock_state: "low_stock",
  stock_state_display: "Tồn thấp",
  archived_at: null,
  archive_reason: null,
  version: 1,
  created_at: "2026-07-23T00:00:00Z",
  updated_at: "2026-07-23T00:00:00Z",
} as const;

export const balanceFixture = {
  id: inventoryIds.position,
  part_id: inventoryIds.part,
  part_number: partFixture.part_number,
  part_name_vi: partFixture.name_vi,
  lifecycle_status: "active",
  stock_location_id: inventoryIds.location,
  stock_location_code: stockLocationFixture.code,
  stock_location_name: stockLocationFixture.name,
  stock_location_status: "active",
  unit_of_measure_id: inventoryIds.unit,
  unit_code: "EA",
  unit_symbol: "cái",
  on_hand_quantity: 3,
  reserved_quantity: 1,
  available_quantity: 2,
  minimum_stock: 2,
  reorder_point: 4,
  maximum_stock: 12,
  stock_state: "low_stock",
  stock_state_display: "Tồn thấp",
  suggested_reorder_quantity: 9,
  version: 2,
  updated_at: "2026-07-23T01:00:00Z",
} as const;

export const movementFixture = {
  id: inventoryIds.movement,
  movement_number: "MOV-2026-000001",
  part_id: inventoryIds.part,
  part_number: partFixture.part_number,
  part_name_vi: partFixture.name_vi,
  stock_location_id: inventoryIds.location,
  stock_location_code: stockLocationFixture.code,
  stock_location_name: stockLocationFixture.name,
  quantity: 3,
  unit_of_measure_id: inventoryIds.unit,
  unit_code: "EA",
  unit_symbol: "cái",
  movement_type: "receipt",
  movement_type_display: "Nhập kho",
  business_reference: "DEMO-RECEIPT-001",
  actor_user_id: inventoryIds.user,
  actor_display_name: "Thủ kho demo",
  occurred_at: "2026-07-23T01:00:00Z",
  reason: "Nhập kho phục vụ bảo trì",
  work_order_id: null,
  work_order_number: null,
  source_location_id: null,
  source_location_code: null,
  destination_location_id: null,
  destination_location_code: null,
  transfer_group_id: null,
  unit_cost_snapshot: 250000,
  resulting_on_hand_quantity: 3,
  resulting_reserved_quantity: 1,
  resulting_available_quantity: 2,
  idempotency_key: "inventory-receipt-test",
  created_at: "2026-07-23T01:00:00Z",
} as const;

export const requirementFixture = {
  id: inventoryIds.requirement,
  work_order_id: inventoryIds.workOrder,
  work_order_number: "WO-2026-000001",
  part_id: inventoryIds.part,
  part_number: partFixture.part_number,
  part_name_vi: partFixture.name_vi,
  unit_code: "EA",
  unit_symbol: "cái",
  planned_quantity: 2,
  required_by_date: "2026-07-25",
  source_stock_location_id: inventoryIds.location,
  source_stock_location_code: stockLocationFixture.code,
  source_stock_location_name: stockLocationFixture.name,
  status: "partially_reserved",
  status_display: "Đã giữ một phần",
  notes: "Chuẩn bị trước khi kiểm tra máy phát.",
  reserved_quantity: 1,
  issued_quantity: 0,
  returned_quantity: 0,
  consumed_quantity: 0,
  outstanding_issued_quantity: 0,
  shortage_quantity: 1,
  version: 2,
  created_at: "2026-07-23T01:00:00Z",
  updated_at: "2026-07-23T01:00:00Z",
} as const;

export const reservationFixture = {
  id: inventoryIds.reservation,
  reservation_number: "RSV-2026-000001",
  requirement_id: inventoryIds.requirement,
  work_order_id: inventoryIds.workOrder,
  work_order_number: "WO-2026-000001",
  part_id: inventoryIds.part,
  part_number: partFixture.part_number,
  part_name_vi: partFixture.name_vi,
  stock_location_id: inventoryIds.location,
  stock_location_code: stockLocationFixture.code,
  stock_location_name: stockLocationFixture.name,
  occurrence_number: 1,
  quantity: 1,
  issued_quantity: 0,
  remaining_quantity: 1,
  status: "active",
  status_display: "Đang giữ",
  expires_at: "2026-07-25T00:00:00Z",
  replaced_by_reservation_id: null,
  version: 1,
  created_at: "2026-07-23T01:00:00Z",
  updated_at: "2026-07-23T01:00:00Z",
  events: [
    {
      id: inventoryIds.reservationEvent,
      event_type: "reserved",
      quantity: 1,
      reason: "Giữ cho công việc",
      actor_user_id: inventoryIds.user,
      actor_display_name: "Kỹ sư trưởng demo",
      occurred_at: "2026-07-23T01:00:00Z",
    },
  ],
} as const;

export const issueFixture = {
  id: inventoryIds.issue,
  issue_number: "ISS-2026-000001",
  work_order_id: inventoryIds.workOrder,
  work_order_number: "WO-2026-000001",
  requirement_id: inventoryIds.requirement,
  reservation_id: inventoryIds.reservation,
  part_id: inventoryIds.part,
  part_number: partFixture.part_number,
  part_name_vi: partFixture.name_vi,
  stock_location_id: inventoryIds.location,
  stock_location_code: stockLocationFixture.code,
  stock_location_name: stockLocationFixture.name,
  unit_code: "EA",
  unit_symbol: "cái",
  quantity: 1,
  reserved_quantity_used: 1,
  consumed_quantity: 0,
  returned_quantity: 0,
  outstanding_quantity: 1,
  issued_to_user_id: inventoryIds.user,
  issued_to_display_name: "Kỹ thuật viên demo",
  issued_by_user_id: inventoryIds.user,
  issued_by_display_name: "Thủ kho demo",
  issued_at: "2026-07-23T02:00:00Z",
  reason: "Xuất cho work order",
  movement_id: inventoryIds.movement,
  consumptions: [],
  returns: [],
} as const;

export const workOrderPartsFixture = {
  work_order_id: inventoryIds.workOrder,
  work_order_number: "WO-2026-000001",
  work_order_status: "in_progress",
  work_order_status_display: "Đang thực hiện",
  assigned_to_user_id: inventoryIds.user,
  requirements: [requirementFixture],
  reservations: [reservationFixture],
  issues: [issueFixture],
  movements: [movementFixture],
  total_planned_quantity: 2,
  total_reserved_quantity: 1,
  total_issued_quantity: 1,
  total_returned_quantity: 0,
  net_consumed_quantity: 0,
  open_shortage_count: 1,
  has_unresolved_issued_stock: true,
  completion_policy: "warning_only",
  completion_warning:
    "Work order còn thiếu vật tư hoặc vật tư đã xuất chưa được consume/return.",
} as const;

export const inventoryMetricsFixture = {
  total_active_parts: 8,
  total_on_hand_units: 48,
  total_reserved_units: 4,
  total_available_units: 44,
  low_stock_parts: 1,
  out_of_stock_parts: 1,
  open_shortages: 1,
  work_orders_waiting_for_parts: 1,
  movements_by_type: { receipt: 1, issue: 1 },
  data_notice:
    "Tổng số lượng là chỉ báo vận hành qua nhiều đơn vị tính; không dùng làm định giá.",
} as const;

export function page<T>(items: T[]) {
  return {
    items,
    page: 1,
    page_size: 20,
    total: items.length,
    total_pages: items.length ? 1 : 0,
  };
}
