name: "maintenance_analytics"
version: "1.0.0"
config-version: 2

profile: "maintenance_analytics"

vars:
  reporting_timezone: "Asia/Ho_Chi_Minh"

model-paths:
  - "models"
test-paths:
  - "tests"
macro-paths:
  - "macros"

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  maintenance_analytics:
    staging:
      +materialized: view
      +schema: staging
    warehouse:
      +materialized: table
      +schema: warehouse
    marts:
      +materialized: table
      +schema: marts
