import type {
  AnomalyRecord,
  Asset,
  MaintenanceEvent,
  RecurringIssue,
  RiskContribution,
  SourceDocument,
  Ticket,
} from "@/lib/types";

export const overviewKpis = [
  { label: "Thiết bị rủi ro cao", value: "2", detail: "Cần ưu tiên kiểm tra", tone: "orange" },
  { label: "Ticket đang mở", value: "18", detail: "7 mới, 11 đang xử lý", tone: "amber" },
  { label: "Bảo trì quá hạn", value: "2", detail: "Tối đa 159 ngày", tone: "red" },
  { label: "Tỷ lệ xử lý", value: "57,14%", detail: "24/42 ticket đã xử lý", tone: "green" },
] as const;

export const secondaryOverviewStats = [
  { label: "Tổng thiết bị", value: "27" },
  { label: "Bất thường gần đây", value: "6" },
  { label: "Nhóm lỗi lặp lại", value: "4" },
  { label: "Batch dữ liệu", value: "30/04/2026" },
] as const;

export const riskDistribution = [
  { name: "Thấp", value: 14, color: "#16a34a" },
  { name: "Trung bình", value: 11, color: "#d97706" },
  { name: "Cao", value: 2, color: "#ea580c" },
  { name: "Khẩn cấp", value: 0, color: "#dc2626" },
];

export const ticketStatusDistribution = [
  { name: "Mới tạo", value: 7, color: "#2563eb" },
  { name: "Đang xử lý", value: 11, color: "#d97706" },
  { name: "Đã xử lý", value: 24, color: "#16a34a" },
];

export const preventiveDistribution = [
  { name: "Chưa đến hạn", value: 23, color: "#16a34a" },
  { name: "Sắp đến hạn", value: 2, color: "#d97706" },
  { name: "Quá hạn", value: 2, color: "#dc2626" },
];

export const assets: Asset[] = [
  {
    id: "GENERATOR_002",
    name: "Máy phát điện dự phòng 002",
    type: "Máy phát điện",
    location: "Sân thượng phía Đông",
    criticality: "Rất cao",
    status: "Đang hoạt động",
    riskScore: 63.89,
    riskLevel: "Cao",
    maintenanceStatus: "Quá hạn",
    lastMaintenance: "22/11/2025",
    nextMaintenance: "22/11/2025",
    overdueDays: 159,
    unresolvedTickets: 2,
    contributingFactors: "Điện áp ắc quy và thời gian vận hành lệch mức tham chiếu",
    recommendedAction: "Kiểm tra ắc quy, dầu, nước làm mát và chạy thử có tải.",
  },
  {
    id: "GENERATOR_001",
    name: "Máy phát điện dự phòng 001",
    type: "Máy phát điện",
    location: "Tầng kỹ thuật B1",
    criticality: "Rất cao",
    status: "Đang hoạt động",
    riskScore: 61.42,
    riskLevel: "Cao",
    maintenanceStatus: "Quá hạn",
    lastMaintenance: "05/12/2025",
    nextMaintenance: "05/12/2025",
    overdueDays: 146,
    unresolvedTickets: 2,
    contributingFactors: "Nhiệt độ vận hành cao hơn xu hướng 7 ngày",
    recommendedAction: "Kiểm tra hệ thống làm mát và lịch chạy thử gần nhất.",
  },
  {
    id: "HVAC_001",
    name: "Cụm điều hòa trung tâm 001",
    type: "HVAC",
    location: "Tầng kỹ thuật 12",
    criticality: "Cao",
    status: "Đang hoạt động",
    riskScore: 45.87,
    riskLevel: "Trung bình",
    maintenanceStatus: "Sắp đến hạn",
    lastMaintenance: "02/02/2026",
    nextMaintenance: "04/05/2026",
    overdueDays: 0,
    unresolvedTickets: 1,
    contributingFactors: "Điện năng tiêu thụ tăng so với trung bình lăn",
    recommendedAction: "Theo dõi tải lạnh và kiểm tra lọc gió trong kỳ kế tiếp.",
  },
  {
    id: "PUMP_001",
    name: "Bơm cấp nước 001",
    type: "Bơm nước",
    location: "Phòng bơm B2",
    criticality: "Cao",
    status: "Đang hoạt động",
    riskScore: 44.86,
    riskLevel: "Trung bình",
    maintenanceStatus: "Chưa đến hạn",
    lastMaintenance: "18/03/2026",
    nextMaintenance: "18/06/2026",
    overdueDays: 0,
    unresolvedTickets: 1,
    contributingFactors: "Độ rung tăng nhẹ ở ca vận hành cuối",
    recommendedAction: "Kiểm tra căn chỉnh và ổ bi trong lần kiểm tra kế hoạch.",
  },
  {
    id: "PUMP_002",
    name: "Bơm cấp nước 002",
    type: "Bơm nước",
    location: "Phòng bơm B2",
    criticality: "Cao",
    status: "Đang hoạt động",
    riskScore: 42.43,
    riskLevel: "Trung bình",
    maintenanceStatus: "Chưa đến hạn",
    lastMaintenance: "21/03/2026",
    nextMaintenance: "21/06/2026",
    overdueDays: 0,
    unresolvedTickets: 1,
    contributingFactors: "Không phát hiện bất thường mới",
    recommendedAction: "Tiếp tục theo dõi theo lịch bảo trì định kỳ.",
  },
  {
    id: "ELEVATOR_001",
    name: "Thang máy khách 001",
    type: "Thang máy",
    location: "Sảnh tháp A",
    criticality: "Rất cao",
    status: "Đang hoạt động",
    riskScore: 35.2,
    riskLevel: "Trung bình",
    maintenanceStatus: "Sắp đến hạn",
    lastMaintenance: "10/04/2026",
    nextMaintenance: "05/05/2026",
    overdueDays: 0,
    unresolvedTickets: 0,
    contributingFactors: "Thời gian vận hành tăng theo nhu cầu sử dụng",
    recommendedAction: "Thực hiện kiểm tra định kỳ theo checklist thang máy.",
  },
  {
    id: "FIRE_PUMP_001",
    name: "Bơm chữa cháy chính 001",
    type: "PCCC",
    location: "Phòng bơm PCCC B1",
    criticality: "Rất cao",
    status: "Sẵn sàng",
    riskScore: 24.75,
    riskLevel: "Thấp",
    maintenanceStatus: "Chưa đến hạn",
    lastMaintenance: "15/04/2026",
    nextMaintenance: "15/05/2026",
    overdueDays: 0,
    unresolvedTickets: 0,
    contributingFactors: "Không phát hiện bất thường mới",
    recommendedAction: "Duy trì lịch chạy thử và ghi nhận áp suất.",
  },
  {
    id: "HVAC_002",
    name: "Cụm điều hòa trung tâm 002",
    type: "HVAC",
    location: "Tầng kỹ thuật 8",
    criticality: "Cao",
    status: "Đang hoạt động",
    riskScore: 21.64,
    riskLevel: "Thấp",
    maintenanceStatus: "Chưa đến hạn",
    lastMaintenance: "25/03/2026",
    nextMaintenance: "25/06/2026",
    overdueDays: 0,
    unresolvedTickets: 1,
    contributingFactors: "Không phát hiện bất thường mới",
    recommendedAction: "Tiếp tục theo dõi điện năng và nhiệt độ hồi gió.",
  },
];

export const tickets: Ticket[] = [
  {
    id: "TCK-000042",
    assetId: "GENERATOR_001",
    summary: "Nhiệt độ máy tăng khi chạy thử",
    description: "Nhiệt độ động cơ tăng nhanh sau 20 phút chạy thử không tải.",
    failureCategory: "Hệ thống làm mát",
    priority: "Khẩn cấp",
    status: "new",
    technician: "Chưa phân công",
    createdAt: "30/04/2026 09:15",
    updatedAt: "30/04/2026 09:15",
    waitingTime: "2 giờ",
  },
  {
    id: "TCK-000041",
    assetId: "GENERATOR_002",
    summary: "Điện áp ắc quy khởi động thấp",
    description: "Điện áp ắc quy thấp hơn mức tham chiếu trong lần chạy thử gần nhất.",
    failureCategory: "Hệ thống điện",
    priority: "Khẩn cấp",
    status: "new",
    technician: "Chưa phân công",
    createdAt: "29/04/2026 14:20",
    updatedAt: "29/04/2026 14:20",
    waitingTime: "19 giờ",
  },
  {
    id: "TCK-000040",
    assetId: "HVAC_002",
    summary: "Nhiệt độ hồi gió dao động",
    description: "Nhiệt độ hồi gió dao động ngoài khoảng vận hành thông thường.",
    failureCategory: "Điều khiển nhiệt độ",
    priority: "Cao",
    status: "in_progress",
    technician: "Nguyễn Minh Tuấn",
    createdAt: "28/04/2026 10:05",
    updatedAt: "30/04/2026 08:30",
    waitingTime: "2 ngày",
  },
  {
    id: "TCK-000039",
    assetId: "PUMP_001",
    summary: "Độ rung bơm tăng nhẹ",
    description: "Độ rung tăng ở cuối ca, chưa ghi nhận rò rỉ hoặc tiếng ồn lớn.",
    failureCategory: "Cơ khí",
    priority: "Cao",
    status: "in_progress",
    technician: "Trần Quốc Huy",
    createdAt: "27/04/2026 16:40",
    updatedAt: "29/04/2026 11:10",
    waitingTime: "3 ngày",
  },
  {
    id: "TCK-000038",
    assetId: "GENERATOR_002",
    summary: "Lịch chạy thử có tải chưa hoàn tất",
    description: "Cần xác nhận tình trạng dầu, nước làm mát và tải trước khi chạy thử.",
    failureCategory: "Bảo trì phòng ngừa",
    priority: "Cao",
    status: "in_progress",
    technician: "Lê Hoàng Nam",
    createdAt: "25/04/2026 08:30",
    updatedAt: "29/04/2026 15:45",
    waitingTime: "5 ngày",
  },
  {
    id: "TCK-000037",
    assetId: "ELEVATOR_001",
    summary: "Tiếng ồn khi đóng cửa tầng 8",
    description: "Kiểm tra ray cửa và cảm biến đóng cửa tại tầng 8.",
    failureCategory: "Cửa tầng",
    priority: "Trung bình",
    status: "new",
    technician: "Phạm Gia Bảo",
    createdAt: "24/04/2026 13:12",
    updatedAt: "24/04/2026 13:12",
    waitingTime: "6 ngày",
  },
  {
    id: "TCK-000036",
    assetId: "FIRE_PUMP_001",
    summary: "Kiểm tra áp suất chạy thử",
    description: "Đã kiểm tra áp suất đầu ra và ghi nhận trong giới hạn vận hành.",
    failureCategory: "Kiểm tra định kỳ",
    priority: "Trung bình",
    status: "resolved",
    technician: "Vũ Đức Anh",
    createdAt: "22/04/2026 09:00",
    updatedAt: "22/04/2026 11:20",
    waitingTime: "2 giờ 20 phút",
  },
  {
    id: "TCK-000035",
    assetId: "HVAC_001",
    summary: "Vệ sinh lọc gió AHU",
    description: "Lọc gió đã được vệ sinh và kiểm tra chênh áp sau bảo trì.",
    failureCategory: "Bảo trì phòng ngừa",
    priority: "Thấp",
    status: "resolved",
    technician: "Nguyễn Minh Tuấn",
    createdAt: "20/04/2026 08:10",
    updatedAt: "20/04/2026 12:45",
    waitingTime: "4 giờ 35 phút",
  },
  {
    id: "TCK-000034",
    assetId: "PUMP_002",
    summary: "Kiểm tra phớt bơm",
    description: "Không phát hiện rò rỉ, phớt bơm và khớp nối hoạt động bình thường.",
    failureCategory: "Cơ khí",
    priority: "Trung bình",
    status: "resolved",
    technician: "Trần Quốc Huy",
    createdAt: "18/04/2026 14:05",
    updatedAt: "18/04/2026 16:25",
    waitingTime: "2 giờ 20 phút",
  },
];

export const anomalies: AnomalyRecord[] = [
  {
    id: "ANM-20260430-01",
    date: "30/04/2026",
    assetId: "GENERATOR_002",
    assetType: "Máy phát điện",
    anomalyType: "Kết hợp rule và Isolation Forest",
    metric: "Điện áp ắc quy / runtime",
    change: "Điện áp thấp, runtime lệch xu hướng 7 ngày",
    severity: "Ưu tiên",
    score: 0.86,
    reason: "Điện áp ắc quy thấp và runtime lệch mức tham chiếu.",
    relatedAction: "Đo điện áp, kiểm tra bộ sạc và lịch chạy thử.",
  },
  {
    id: "ANM-20260430-02",
    date: "30/04/2026",
    assetId: "GENERATOR_001",
    assetType: "Máy phát điện",
    anomalyType: "Bất thường theo rule",
    metric: "Nhiệt độ động cơ",
    change: "Vượt ngưỡng vận hành theo loại thiết bị",
    severity: "Ưu tiên",
    score: 0.81,
    reason: "Nhiệt độ cao hơn ngưỡng vận hành theo loại thiết bị.",
    relatedAction: "Kiểm tra hệ thống làm mát trước lần chạy thử tiếp theo.",
  },
  {
    id: "ANM-20260429-01",
    date: "29/04/2026",
    assetId: "PUMP_001",
    assetType: "Bơm nước",
    anomalyType: "Isolation Forest",
    metric: "Độ rung",
    change: "Tăng so với phân bố lịch sử của thiết bị",
    severity: "Cảnh báo",
    score: 0.68,
    reason: "Độ rung tăng so với phân bố lịch sử của thiết bị.",
    relatedAction: "Kiểm tra căn chỉnh, ổ bi và tiếng ồn tại hiện trường.",
  },
  {
    id: "ANM-20260428-01",
    date: "28/04/2026",
    assetId: "HVAC_001",
    assetType: "HVAC",
    anomalyType: "Bất thường theo rule",
    metric: "Điện năng / nhiệt độ hồi gió",
    change: "Cùng tăng so với mức tham chiếu",
    severity: "Cảnh báo",
    score: 0.61,
    reason: "Điện năng tăng đồng thời với nhiệt độ hồi gió cao.",
    relatedAction: "Kiểm tra tải lạnh, lọc gió và điều kiện vận hành.",
  },
  {
    id: "ANM-20260427-01",
    date: "27/04/2026",
    assetId: "HVAC_002",
    assetType: "HVAC",
    anomalyType: "Isolation Forest",
    metric: "Nhiệt độ hồi gió",
    change: "Dao động khác lịch sử gần đây",
    severity: "Theo dõi",
    score: 0.58,
    reason: "Mẫu nhiệt độ dao động khác lịch sử gần đây.",
    relatedAction: "Theo dõi thêm một batch và đối chiếu cảm biến.",
  },
  {
    id: "ANM-20260425-01",
    date: "25/04/2026",
    assetId: "ELEVATOR_001",
    assetType: "Thang máy",
    anomalyType: "Isolation Forest",
    metric: "Runtime",
    change: "Tăng so với trung bình lăn 7 ngày",
    severity: "Theo dõi",
    score: 0.51,
    reason: "Runtime tăng so với trung bình lăn 7 ngày.",
    relatedAction: "Đối chiếu lưu lượng sử dụng và lịch kiểm tra định kỳ.",
  },
];

export const recurringIssues: RecurringIssue[] = [
  { assetId: "GENERATOR_002", category: "Nhiệt độ vận hành cao", occurrences: 5, latestDate: "30/04/2026", unresolvedCount: 2, recurrenceFlag: true },
  { assetId: "HVAC_001", category: "Dao động nhiệt độ hồi gió", occurrences: 4, latestDate: "28/04/2026", unresolvedCount: 1, recurrenceFlag: true },
  { assetId: "PUMP_001", category: "Độ rung tăng", occurrences: 3, latestDate: "27/04/2026", unresolvedCount: 1, recurrenceFlag: true },
  { assetId: "ELEVATOR_001", category: "Tiếng ồn cửa tầng", occurrences: 3, latestDate: "24/04/2026", unresolvedCount: 0, recurrenceFlag: true },
];

export const anomalyTrend = [
  { date: "24/04", count: 1, averageScore: 0.41 },
  { date: "25/04", count: 2, averageScore: 0.48 },
  { date: "26/04", count: 1, averageScore: 0.39 },
  { date: "27/04", count: 3, averageScore: 0.55 },
  { date: "28/04", count: 2, averageScore: 0.57 },
  { date: "29/04", count: 2, averageScore: 0.63 },
  { date: "30/04", count: 4, averageScore: 0.72 },
];

export const generatorRiskHistory = [
  { date: "24/04", score: 49.2 },
  { date: "25/04", score: 51.8 },
  { date: "26/04", score: 52.6 },
  { date: "27/04", score: 55.3 },
  { date: "28/04", score: 58.7 },
  { date: "29/04", score: 61.4 },
  { date: "30/04", score: 63.89 },
];

export const generatorRiskContributions: RiskContribution[] = [
  { factor: "Bất thường", value: 24.4, explanation: "Tín hiệu bất thường từ rule và Isolation Forest." },
  { factor: "Bảo trì quá hạn", value: 20, explanation: "Lịch bảo trì đã quá hạn 159 ngày." },
  { factor: "Ticket chưa xử lý", value: 10, explanation: "Có 2 ticket liên quan chưa hoàn tất." },
  { factor: "Mức độ quan trọng", value: 7.5, explanation: "Thiết bị được phân loại rất quan trọng." },
  { factor: "Runtime", value: 1.99, explanation: "Runtime gần đây lệch xu hướng tham chiếu." },
];

export const generatorMaintenance: MaintenanceEvent[] = [
  {
    id: "LOG-000086",
    date: "22/11/2025",
    result: "Hoàn tất, cần theo dõi",
    actions: "Thay dầu, kiểm tra nước làm mát và chạy thử không tải.",
    technician: "Lê Hoàng Nam",
    followUp: true,
    nextMaintenance: "22/03/2026",
  },
  {
    id: "LOG-000071",
    date: "18/08/2025",
    result: "Hoàn tất",
    actions: "Vệ sinh đầu cực ắc quy, đo điện áp và kiểm tra rò rỉ.",
    technician: "Phạm Gia Bảo",
    followUp: false,
    nextMaintenance: "18/12/2025",
  },
  {
    id: "LOG-000052",
    date: "20/05/2025",
    result: "Hoàn tất",
    actions: "Kiểm tra bộ sạc, dây curoa và mức nhiên liệu.",
    technician: "Lê Hoàng Nam",
    followUp: false,
    nextMaintenance: "18/09/2025",
  },
];

export const copilotSources: SourceDocument[] = [
  {
    title: "SOP kiểm tra máy phát điện dự phòng",
    section: "Mục 3.2 - Hệ thống khởi động",
    relevance: 0.91,
    excerpt: "Đo điện áp ắc quy, kiểm tra đầu cực và bộ sạc trước khi chạy thử.",
  },
  {
    title: "Checklist bảo trì máy phát điện hàng tháng",
    section: "Bước 4 - Chạy thử có tải",
    relevance: 0.86,
    excerpt: "Xác nhận dầu, nước làm mát, nhiên liệu và điều kiện an toàn trước khi đóng tải.",
  },
];

export const copilotSuggestedQuestions = [
  "Vì sao thiết bị đang rủi ro cao?",
  "Checklist kiểm tra ắc quy gồm những gì?",
  "Cần xác minh gì trước khi chạy thử có tải?",
  "Khi nào cần đánh dấu theo dõi?",
] as const;
